# Generated by Django 4.2 on 2024-09-03 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_account_accountemailauthcode_loginlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
            ],
            options={
                "db_table": "plugin_developer",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "插件"), (2, "应用"), (3, "链接")],
                        default=3,
                        verbose_name="版本类别",
                    ),
                ),
                ("icon_url", models.URLField(verbose_name="插件图标")),
            ],
            options={
                "db_table": "plugin",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "plugin_tag",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="PluginVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("version_no", models.CharField(max_length=50, verbose_name="版本号")),
                ("description", models.TextField(verbose_name="版本说明")),
                ("attachment_url", models.URLField(verbose_name="文件链接")),
                (
                    "attachment_size",
                    models.BigIntegerField(null=True, verbose_name="文件大小"),
                ),
                (
                    "execution_file_path",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="应用入口"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "新建"),
                            (2, "待审核"),
                            (3, "已审核"),
                            (4, "发布"),
                            (5, "审核不通过"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发布时间"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        db_table="r_plugin_version_developer", to="plugin.developer"
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.account",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.account",
                        verbose_name="删除人",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="plugin.plugin",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        db_table="r_plugin_version_tag",
                        related_name="tags",
                        to="plugin.tag",
                    ),
                ),
                (
                    "updated_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.account",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "plugin_version",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="PluginCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "created_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.account",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.account",
                        verbose_name="删除人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="plugin.plugincategory",
                        verbose_name="父级分类",
                    ),
                ),
                (
                    "updated_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.account",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "plugin_category",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="plugin",
            name="categories",
            field=models.ManyToManyField(
                db_table="r_plugin_category",
                related_name="plugin_category",
                to="plugin.plugincategory",
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="created_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.account",
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="deleted_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.account",
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="updated_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.account",
                verbose_name="更新人",
            ),
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "打开"), (2, "安装"), (3, "运行")],
                        default=1,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                        verbose_name="操作者",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="plugin.pluginversion",
                    ),
                ),
            ],
            options={
                "db_table": "plugin_operation_log",
                "ordering": ("-id",),
            },
        ),
    ]
