# Generated by Django 4.2 on 2024-10-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="developer",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="operationlog",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="plugin",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="plugincategory",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="pluginversion",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveField(
            model_name="pluginversion",
            name="tags",
        ),
        migrations.AddField(
            model_name="plugin",
            name="tags",
            field=models.ManyToManyField(
                db_table="r_plugin_tag", related_name="tags", to="plugin.tag"
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="is_external",
            field=models.BooleanField(default=False, verbose_name="是否外部插件"),
        ),
        migrations.AlterField(
            model_name="pluginversion",
            name="description",
            field=models.TextField(verbose_name="更新说明"),
        ),
        migrations.AddField(
            model_name="plugin",
            name="description",
            field=models.TextField(default="", verbose_name="插件说明"),
        ),
    ]
