# Generated by Django 4.2 on 2025-01-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0002_alter_developer_options_alter_operationlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="link",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="插件链接"
            ),
        ),
    ]
