# Generated by Django 4.2 on 2025-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0003_plugin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='user_manual',
            field=models.URLField(null=True, verbose_name='User Manual Link'),
        ),
    ]
