version: '3.8'

services:
  db:
    image: postgres:15.8
    container_name: django_pgsql_db
    environment:
      POSTGRES_DB: ${DATABASE_POSTGRES_NAME}
      POSTGRES_USER: ${DATABASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWORD}
      POSTGRES_PORT: ${DATABASE_POSTGRES_PORT}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_pgsql_network

  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django_pgsql_network

volumes:
  postgres_data:

networks:
  django_pgsql_network:
