services:
  archi_ai_app_store_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: archi_ai_app_store_server:latest
    container_name: archi_ai_app_store_server
    ports:
      - 8000:8007
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py migrate &&
        python3 manage.py createcachetable &&
        gunicorn server.wsgi:application -c gunicorn_config.py --bind 0.0.0.0:8000
    volumes:
    - log_files:/app/logs


volumes:
  log_files:
