# Generated by Django 4.2 on 2025-03-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('major_version', models.IntegerField(verbose_name='主版本号')),
                ('minor_version', models.IntegerField(verbose_name='次版本号')),
                ('patch_version', models.IntegerField(verbose_name='修订号')),
                ('is_active', models.BooleanField(default=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('description', models.TextField(default='', verbose_name='更新说明')),
                ('version_str', models.CharField(max_length=32)),
                ('cos_dir', models.URLField(max_length=512, verbose_name='下载地址')),
            ],
            options={
                'db_table': 'client',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='clientversion',
            index=models.Index(fields=['version_str'], name='client_version_fd8e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientversion',
            index=models.Index(fields=['major_version', 'minor_version', 'patch_version'], name='client_major_v_07178c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientversion',
            unique_together={('major_version', 'minor_version', 'patch_version')},
        ),
    ]
