# Generated by Django 4.2 on 2024-08-23 07:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=100)),
                ('access_token', models.CharField(default='', max_length=50)),
                ('token_expired', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_super', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_account',
            },
        ),
    ]
