# Generated by Django 4.2 on 2024-08-30 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('can_admin', models.BooleanField(default=False)),
                ('is_super', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('access_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('token_expired', models.DateTimeField(default=None, null=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('last_ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AccountEmailAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_success', models.BooleanField(default=False)),
                ('expired', models.DateTimeField(default=None, null=True)),
                ('for_what', models.SmallIntegerField(choices=[(1, '用户注册'), (2, '修改密码')])),
            ],
            options={
                'db_table': 'account_email_auth_code',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('is_success', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'login_log',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='ModelAccount',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
    ]
