# Generated by Django 4.2 on 2024-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_accountemailauthcode_accountemailauthlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
