# Generated by Django 4.2 on 2024-09-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_accountemailauthcode_loginlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
