# Generated by Django 4.2 on 2024-08-28 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='accountemailauthcode',
            name='for_what',
            field=models.SmallIntegerField(choices=[(1, 'Register'), (2, 'Password')]),
        ),
        migrations.AlterField(
            model_name='accountemailauthlog',
            name='for_what',
            field=models.SmallIntegerField(choices=[(1, 'Register'), (2, 'Password')]),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
    ]
